_decoder:
    value: SkipDecoderBlock
_encoder:
    value: DefaultEncoderBlock
_wandb:
    value:
        cli_version: 0.18.3
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 9
                - 53
                - 54
                - 55
                - 103
                - 106
            "2":
                - 1
                - 5
                - 9
                - 53
                - 54
                - 55
                - 103
                - 106
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.9
            "5": 0.18.3
            "8":
                - 1
                - 5
            "12": 0.18.3
            "13": linux-x86_64
config:
    value: '{''has_cbm'': True, ''lr'': 0.0005, ''hidden_dim'': 256, ''beta'': 1e-05, ''input_dim'': 9224, ''latent_dim'': 128, ''n_concepts'': 9, ''min_bottleneck_size'': 128, ''independent_training'': True, ''concepts_hp'': 0.005, ''orthogonality_hp'': 0.2, ''use_soft_concepts'': False}'
orthogonality_loss:
    value: cross_covariance_loss
