defaults:
  - dataset: synthetic_1.yaml
  - intervention: synthetic/intervention_0
  - constants: default.yaml
  - model: vae.yaml
  - modify: default.yaml
  - experiment: null
  - _self_


wandb:
  experiment: conceptlab
  project: conceptlab
  entity: null


trainer:
  max_epochs: 250

plotting:
  plot: False
  plot_path: plots

model:
  use_gaussian_mixture_KL: False


test_intervention: False
test_integration: ['modularity']

save_checkpoints: True
DEBUG: False
save_generated_data: False
