defaults:
  - _self_
  - dataset: default.yaml
  - constants: default.yaml
  - model: vae.yaml
  - modify: default.yaml
  - experiment: null


wandb:
  experiment: conceptlab
  project: conceptlab


trainer:
  max_epochs: 200

plotting:
  plot: False
  plot_path: plots

test_intervention: False
test_integration: ['modularity']

save_checkpoints: True
DEBUG: False
