defaults:
  - _self_
  - constants: default.yaml
  - model: cb_vae.yaml
  - analysis: default.yaml
  - dataset: default.yaml


wandb:
  experiment: conceptlab
  project: conceptlab
  entity: null


trainer:
  max_epochs: 200

plotting:
  plot: False
  plot_path: plots

model:
  use_gaussian_mixture_KL: False

save_checkpoints: False
save_generated_data: False
