defaults:
  - _self_
  - dataset: default.yaml
  - constants: default.yaml
  - model: vae.yaml
  - experiment: null
  - modify: default.yaml
  
  
trainer:
  max_epochs: 100


plotting:
  plot: False
  plot_path: null

test_intervention: False
test_integration: ['modularity']
